name: constata
description: Apontamento Digital - Constata.

publish_to: "none"
version: 1.7.1+15

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  platform: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.0.6
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  dio: ^5.2.1
  path_provider: ^2.0.6
  uuid: ^3.0.5
  provider: ^6.0.1
  flutter_masked_text2: ^0.9.1
  animated_splash_screen: ^1.1.0
  flutter_slidable: ^2.0.0
  flutter_speed_dial: ^6.0.0
  search_choices: ^2.1.4
  flutter_staggered_animations: ^1.1.1
  firebase_crashlytics: ^3.3.3
  firebase_messaging: ^14.6.3
  overlay_support: ^2.1.0
  flutter_local_notifications: ^13.0.0
  flutter_native_timezone: ^2.0.0
  firebase_core: ^2.14.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
