name: Build



on:
  push:
    branches:
      - main

# the follow line allow this script to be started manually.
  workflow_dispatch:

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.4'
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build appbundle
