name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'adopt'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
      env:
        PROPERTIES_PATH: "./android/key.properties"
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: echo $KEY_JKS > key.jks 
              # Creating the key.properties file
    - run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ${{env.PROPERTIES_PATH}}
          echo storePassword=\${{ secrets.KEY_PASSWORD }} >> ${{env.PROPERTIES_PATH}}
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ${{env.PROPERTIES_PATH}}
    - run: echo "${{ secrets.KEY_JKS }}" | base64 --decode > android/app/key.jks
    - run: flutter pub get
    - run: flutter build apk
    - uses: actions/upload-artifact@v3
      with:
        name: Release artifact
        path: app/build/outputs/apk/ourbuildtype/release/app-artifact-*.apk
