name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ... (outros passos aqui)

      # Corrigindo os comandos echo e encadeando-os usando &&
    - run: echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> filename.txt
    - run: echo "storePassword=${{ secrets.KEY_PASSWORD }}" >> filename.txt
    - run: echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> filename.txt


      # ... (outros passos aqui)
