name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'adopt'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'dev'
      env:
          PLAY_STORE_UPLOAD_KEY: ${{ secrets.KEY_JKS }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
    - run: |
          echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > app/upload-keystore.jks
          echo "storeFile=upload-keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties
          working-directory: android
          - run: flutter pub get
        
        
    
   
    - uses: actions/upload-artifact@v3
      with:
        name: Release artifact
        path: app/build/outputs/apk/ourbuildtype/release/app-artifact-*.apk
