name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'adopt'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'dev'
      env:
        KEY_JKS: ${{ secrets.KEY_JKS }}
        KEY_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
        ALIAS_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: echo $KEY_JKS > key.jks && flutter pub get && flutter test && flutter build appbundle
    - uses: actions/upload-artifact@v3
      with:
        name: release
        path: build/app/outputs/bundle/release/
