name: Build



on:
  push:
    branches:
      - main

# the follow line allow this script to be started manually.
  workflow_dispatch:

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
      
    - name: prepare key.jks & key.properties files
      env:
        FS_KEYSTORE_FILE: ${{ secrets.KEY }}
        run: |
          echo "convert base64 strings to files"
          echo "$FS_KEYSTORE_FILE" >> key.jks.base64
          echo "done with base64 files creation"
          base64 --decode key.jks.base64 > key.jks
          echo "done key.jks"
        working-directory: 'android'
        
        
        
        
        
    
    
    
    
    
    
