name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'dev'
      env:
        PLAY_STORE_UPLOAD_KEY: ${{ secrets.KEY_JKS }}
        KEYSTORE_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEYSTORE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        KEYSTORE_STORE_PASSWORD: ${{ secrets.ALIAS_PASSWORD }}
    - name: Set up keystore
      run: |
        echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > ${{ secrets.KEY_JKS }}
        echo "storeFile=upload-keystore.jks" >> android/key.properties
        echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> android/key.properties
        echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> android/key.properties
        echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> android/key.properties
      working-directory: ${{ github.workspace }}

    - name: Flutter pub get
      run: flutter pub get
      working-directory: ${{ github.workspace }}
   
    - name: Build APK
      run: flutter build apk --release
      working-directory: ${{ github.workspace }}
        
    - uses: actions/upload-artifact@v3
      with:
        name: Release artifact
        path: ${{ github.workspace }}/build/app/outputs/flutter-apk/app-release.apk
